### PR TITLE
Manage popup scenario.

### LINKED ISSUE #5: [3pt]  - Add comments counter - Student B
Even if the API gives you the number of comments you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Comments pop up.

Respect the following rules:

- Each counter should be implemented as a separate module.
- A counter function should look for specific DOM elements (e.g. for the comments counter it should look for comments) and make the counting based on what is actually displayed on the page.
- A counter function should cover all the edge cases you can think about.

### LINKED ISSUE #8: [4pt]  - Create feature: add new comment - Student B
Implement the "add new comment" form on the Comments pop up according to the wireframe:

Screenshot 2021-06-27 at 22 32 36

When the user clicks on the "Comment" button, the data is recorded in the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) and the screen is updated.

### LINKED ISSUE #11: [3pt]  - Display comments for a given item on the Comments pop-up - Student B
When the popup loads, the webapp retrieves data from the [Involvement API](https://www.notion.so/microverse/Involvement-API-869e60b5ad104603aa6db59e08150270) to show the item comments.

Screenshot 2021-06-27 at 22 21 00

This task **does not** include the counter of the comments.

### LINKED ISSUE #14: [4pt]  -Display Comments pop up with selected item's details - Student B
Create a comments popup only with the top section (displaying details of the selected item)

Screenshot 2021-06-27 at 22 10 45

When the popup loads, the webapp retrieves data from the selected API and shows details about the selected item.

Add event to button prepared by your teammate that will open your popup. You need to communicate with your team member to make sure that you do not block each other (most likely the easiest solution is to merge the list of items feature to the dev branch before you try to add that event).

### PR DESCRIPTION
**Pull request by kambereBr**
- Handles item details (image / title / description)
- Extracts all dom elements (image / title /description / list / form)
- Handles close event by clearing all elements

### CODE REVIEW

**Comment by Felipe-Perez-Ferraro** [comment]
👏 AMAZING JOB 👏 
- I really liked the way you organized your files with es6 modules.
- Nice use of javascript code by ussing Javascript Classes.
- Very good method implement to check if all form fields are completed.

**Review by mahammad-mostafa — CHANGES_REQUESTED** [review]
# What is awesome 👏🏻
✅ Excellent idea of building a separate `dom` module
✅ Good form checks for empty fields

# Suggestions 👌🏻
💡 What about making the `dom` module class where you extract node elements when it is initialized? It will make it much cleaner

💡 Do you think splitting all method in `popup` module will be better? It could make your code more readable & testable

**Comment by kambereBr** [comment]
Thanks @Felipe-Perez-Ferraro, @mahammad-mostafa for your review. 
I've applied your suggestions, please have a look on it and let me know if there's other thing to change.

**Review by mahammad-mostafa — CHANGES_REQUESTED** [review]
# Awesome changes @kambereBr  👏🏻
- ✅ Refactored `dom` module to be a class.
- ✅ Followed a name pattern for all element nodes.
- ✅ Splitted `renderPopup` into two methods.

# Advised suggestions 👌🏻
- 💡 No need to call `renderPopup` inside the constructor. The `network` module will call `renderPopup` directly for opening new popups.
- 💡 No need to pass targetType to `renderDetails` method. All data related to involvement api should be handled by `renderInvolvement` method only.
- 💡 The passed values from `network` module for the `targetType` variable will be (`comments` / `reservations`).
- 💡 Maybe you can split event handling of form submissions in `renderPopup`? Having separate methods for event handlers will make your code readable and testable.

**Review by mahammad-mostafa — APPROVED** [review]
# 🏆 Approved 🏆 
Well done @kambereBr 👏🏻 Your branch have been approved and you can merge :shipit:
🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

**Review by Felipe-Perez-Ferraro — APPROVED** [review]
# 🏆 Approved 🏆 
Well done @kambereBr 👏🏻 Your branch have been approved and you can merge :shipit:
🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇

**Comment by kambereBr** [comment]
Thanks @mahammad-mostafa, @Felipe-Perez-Ferraro

**Pull request merged**
